config/routes.rb
Rails.application.routes.draw do
  resources:books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    validates :name,presence:true,uniqueness:true
    validates :date,presence:true
    validates :price,numericality:{only_integer:true,greater_than:0}
    validates :pages,numericality:{only_integer:true,greater_than:0}
    validates :ISBN,presence:true,uniqueness:true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    rescue_from ActiveRecord::RecordNotFound, with: :not_found
# 如果出現例外訊息就做not_found方法

    def index
        @books=Book.all
    end
    def new
       @book=Book.new
    end
    def create
        @book=Book.new(clean_params)
        if @book.save
            flash[:notice]= "新增成功"
            redirect_to books_path
            
        else 
            flash[:notice]= "資料有誤"
            render :new
        end
    end
    def show
        @book=Book.find(params[:id])
    end

    def edit
        @book=Book.find(params[:id])
    end

    def update
        @book=Book.find(params[:id])
        if @book.update(clean_params)
            redirect_to books_path,notice:"資料已更新完成！！"
        else 
            render :edit
         end
    end

    def destroy
        @book=Book.find(params[:id])
        @book.destroy
        redirect_to books_path ,notice:"已刪除"
    end

    


    private
    def clean_params
        params[:book].permit(:name,:date,:price,:pages,:ISBN)
    end


    def not_found
        # render html:"再試試看ㄌ"
        render file: "#{Rails.root}/public/404.html",
        status:404,layout:false
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(book) do |b|%>
    <%=b.label :name,"書名"%>
    <%= b.text_field :name %><br>

    <%=b.label :date,"出版日期"%>
    <%=b.text_field :date%><br>

    <%=b.label :price,"售價"%>
    <%=b.text_field :price%><br>

    <%=b.label :pages,"頁數"%>
    <%=b.text_field :pages%><br>

    <%=b.label :ISBN,"ISBN"%>
    <%=b.text_field :ISBN %><br>

    <%=b.submit%>
<%end%>

app/views/books/edit.html.erb
<h1>編輯書本資料</h1>

<%=render "form",book:@book%>

<%= link_to "回到書本列表頁",books_path%>

app/views/books/index.html.erb
<h1>書本列表</h1>
<%= link_to "上架書本",  new_book_path%>
<table>
    <thead>
        <tr>
            <td>書名</td>
            <td>出版日期</td>
            <td>售價</td>
            <td>頁數</td>
            <td>ISBN</td>
            <td>操作</td>
        </tr>
    </thead>
    <tbody>
   
       
        <tr>
           <% @books.each do |b| %>
           <td><%=link_to b.name,book_path(id: b.id)%></td>
            <td><%= b.date %></td>
            <td><%= b.price%></td>
            <td><%= b.pages%></td>
            <td><%= b.ISBN%></td>
            <td>
            <%=link_to "刪除",book_path(id: b.id),method: :delete ,data:{ confirm:"確定嗎？"}%>
            <%=link_to "編輯",edit_book_path(id: b.id)%>
            </td>
        </tr>
        <% end %>
      
    </tbody>

</table>

app/views/books/new.html.erb
<h1>新增書本</h1>

<%=render "form",book:@book%>


<%= link_to "回到書本列表頁",books_path%>

app/views/books/show.html.erb
<ol>
<li>書名：<%=@book.name %></li>
<li>出版日期：<%=@book.date %></li>
<li>售價：<%=@book.price %></li>
<li>頁數：<%=@book.pages %></li>
<li>ISBN:<%=@book.ISBN %></li>
</ol>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BOOK</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
  </head>
   
  <body> 
  <%= render "shared/flash" if flash[:notice]%>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<div class="flash">
    <div><%=flash[:notice]%></div>
    <button>X</button>  
</div>